blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/JacksonFergusonDev/pedal-bom-manager/discussions
    about: Please ask questions or discuss ideas here before opening an issue.